export const aiTools = [
  {
    id: "deepseek",
    name: "DeepSeek",
    link: "https://chat.deepseek.com",
    reasoning: 5,
    creativity: 4,
    speed: 5,
    context: "128K",
    description: "Čínský model s extrémně silným reasoning (logickým myšlením). Lidé ho chválí za programování a matematiku - konkuruje Claude 3.5.",
    bestFor: ["Programování a debugging", "Složitá matematika", "Logické úlohy", "Když potřebuješ vysvětlit 'proč'"],
    pros: ["Vynikající reasoning model", "Velmi rychlý", "Dobrá čeština", "Vysoké limity zdarma"],
    cons: ["Slabší na kreativní psaní", "Nemá vlastní obrázky", "Čínský server"],
    capabilities: {
      imageGeneration: false,
      webSearch: false,
      imageAnalysis: false,
      reasoning: true,
    },
    pricing: "Zdarma",
    models: "DeepSeek-V3 (hlavní), DeepSeek-R1 (reasoning)"
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    link: "https://chatgpt.com",
    reasoning: 4,
    creativity: 5,
    speed: 4,
    context: "128K",
    description: "Od OpenAI. Nejznámější a nejuniverzálnější AI. GPT-4o je rychlý a multimodální (text, obrázky, hlas). Nejlepší pro začátečníky.",
    bestFor: ["Univerzální použití", "Generování obrázků", "Hlasové rozhraní", "Když nevíš co použít"],
    pros: ["Umí skoro všechno dobře", "DALL-E 3 na obrázky", "Hlasový režim", "Nejlepší dokumentace"],
    cons: ["Občas 'líný' (nedomyslí odpověď)", "Limity ve free verzi", "Někdy příliš safe/cenzurovaný"],
    capabilities: {
      imageGeneration: true,
      webSearch: true,
      imageAnalysis: true,
      reasoning: true,
    },
    pricing: "Zdarma / Plus $20/měsíc",
    models: "GPT-4o (hlavní free), o1 (reasoning, pro Plus)"
  },
  {
    id: "gemini",
    name: "Gemini",
    link: "https://gemini.google.com",
    reasoning: 4,
    creativity: 4,
    speed: 5,
    context: "2M",
    description: "Google AI s OBROVSKÝM kontextem (2 miliony tokenů). Nejlepší na dlouhé dokumenty, celé knihy. Flash je velmi rychlý.",
    bestFor: ["Dlouhé dokumenty a knihy", "Google Workspace integrace", "Když potřebuješ velkou paměť", "Rychlé odpovědi"],
    pros: ["Obří kontext 2M tokenů", "Velmi rychlý Flash model", "Integrace s Gmail/Docs", "Dobrý multimodální"],
    cons: ["Méně kreativní než GPT/Claude", "Občas moc opatrný", "Slabší čeština než konkurence"],
    capabilities: {
      imageGeneration: true,
      webSearch: true,
      imageAnalysis: true,
      reasoning: true,
    },
    pricing: "Zdarma / Advanced",
    models: "Gemini 2.0 Flash (rychlý), Gemini 1.5 Pro (kontext 2M)"
  },
  {
    id: "claude",
    name: "Claude",
    link: "https://claude.ai",
    reasoning: 5,
    creativity: 5,
    speed: 3,
    context: "200K",
    description: "Od Anthropic. Nejlidštější AI s nejlepší češtinou. Nově má web search + integrace s Google (Drive, Gmail, Calendar)!",
    bestFor: ["Kreativní psaní (články, příběhy)", "Analýza dokumentů", "Programování", "Research s web search"],
    pros: ["Nejlepší čeština (přirozený styl)", "Nově má web search!", "Google integrace (Drive/Gmail)", "Top pro kód a agenty"],
    cons: ["Pomalý", "Limity ve free verzi", "Nemá generování obrázků", "Konzervativní"],
    capabilities: {
      imageGeneration: false,
      webSearch: true,
      imageAnalysis: true,
      reasoning: true,
    },
    pricing: "Zdarma / Pro $20/měsíc",
    models: "Opus 4.5 (top, listopad 2025), Sonnet 4.5 (září 2025), Haiku 4.5 (rychlý)"
  },
  {
    id: "grok",
    name: "Grok",
    link: "https://x.com/i/grok",
    reasoning: 4,
    creativity: 5,
    speed: 5,
    context: "128K",
    description: "Od xAI (Elon Musk). Má přímý přístup k X/Twitter datům v reálném čase. Méně cenzury, vtipný. Aurora pro obrázky.",
    bestFor: ["Aktuální zprávy z X/Twitter", "Když chceš méně cenzury", "Vtipné odpovědi", "Aurora obrázky"],
    pros: ["Real-time přístup k X", "Málo cenzury", "Vtipná personalita", "Aurora - skvělé obrázky"],
    cons: ["Méně seriózní", "Závislý na X datech", "Může být vulgární"],
    capabilities: {
      imageGeneration: true,
      webSearch: true,
      imageAnalysis: true,
      reasoning: true,
    },
    pricing: "Zdarma / X Premium",
    models: "Grok 2 (hlavní), Aurora (generování obrázků)"
  },
  {
    id: "perplexity",
    name: "Perplexity",
    link: "https://perplexity.ai",
    reasoning: 4,
    creativity: 3,
    speed: 5,
    context: "128K",
    description: "AI vyhledávač - ne chatbot. Vždy uvádí zdroje a odkazy. Nejlepší na ověřování faktů a research. Používá různé modely.",
    bestFor: ["Ověřování faktů se zdroji", "Research", "Aktuální informace", "Akademické úkoly"],
    pros: ["Vždy cituje zdroje", "Rychlý", "Používá GPT-4o, Claude", "Dobré na aktuální info"],
    cons: ["Není na kreativní psaní", "Zaměřený jen na vyhledávání", "Slabší konverzace"],
    capabilities: {
      imageGeneration: false,
      webSearch: true,
      imageAnalysis: true,
      reasoning: true,
    },
    pricing: "Zdarma / Pro $20/měsíc",
    models: "Různé (GPT-4o, Claude 3.5, vlastní modely)"
  },
  {
    id: "qwen",
    name: "Qwen",
    link: "https://chat.qwen.ai",
    reasoning: 4,
    creativity: 4,
    speed: 4,
    context: "128K",
    description: "Čínský Alibaba model. Dobrý multimodální - vidí a generuje obrázky. Slušná alternativa k ChatGPT zdarma.",
    bestFor: ["Práce s obrázky (analýza)", "Multimodální úkoly", "Alternativa k ChatGPT"],
    pros: ["Vidí a generuje obrázky", "Dobrý kontext", "Vysoké limity zdarma", "Rychlý"],
    cons: ["Méně známý", "Čínský server", "Slabší než top konkurence", "Horší čeština"],
    capabilities: {
      imageGeneration: true,
      webSearch: true,
      imageAnalysis: true,
      reasoning: true,
    },
    pricing: "Zdarma",
    models: "Qwen2.5 (hlavní model)"
  },
]
